---
title: "Frederick County School Board Race 2024"
output: html_document
date: "2026-06-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#LIBRARIES
```{r}
library(tidyverse)
library(janitor)
library(dplyr)
library(tidyr)
library(DT)
```


# SET UP
```{r}
general1 <- read_csv("https://raw.githubusercontent.com/djnf-data-2026/master/refs/heads/main/data/GENERAL_11PG24_Prov_CVR_SBE_1.csv") |> 
  clean_names()
general2 <- read_csv("https://raw.githubusercontent.com/djnf-data-2026/master/refs/heads/main/data/GENERAL_11PG24_Prov_CVR_SBE.csv") |> 
  clean_names()
general_2024 <- rbind(general1, general2)
school_board <- general_2024 |>
  select(cast_vote_record, precinct, seat_one = board_of_education_500001671, seat_two = x13, seat_three = x14)

seat_one <- school_board |> select(cast_vote_record, precinct, candidate = seat_one)
seat_two <- school_board |> select(cast_vote_record, precinct, candidate = seat_two)
seat_three <- school_board |> select(cast_vote_record, precinct, candidate = seat_three)

school_board <- union(seat_one, seat_two,)
school_board <-union(school_board, seat_three)

```

#SCHOOL BOARD ANALYSIS BY PRECINCT
```{r}


school_board_filter <- school_board|>
  filter(
    !is.na(candidate),
    !candidate %in% c("undervote", "overvote", "or write-in:") #needs reporting to verify accuracy
  ) 


ranked_school_candidates <- school_board |>
   group_by(precinct, candidate)|>
   arrange(candidate)|>
  summarize(votes=n()) |>
  mutate(precinct= substring(precinct, 2))|>
  filter(
    !is.na(candidate),
    !candidate %in% c("undervote", "overvote", "or write-in:") #needs reporting to verify accuracy
  ) |>
  group_by(precinct) |>
  arrange(desc(votes), .by_group = TRUE) |>
  mutate(rank = row_number()) |>
  ungroup()

ranked_school_candidates_by_precinct <- ranked_school_candidates |>
  pivot_wider(
    names_from = rank,
    values_from = c(candidate, votes),
  names_glue = "{.value}_{rank}")|>
 mutate(
    across(
      starts_with("candidate"),
      ~ trimws(gsub("\\s*\\([^)]*\\)", "",.x))
    ))

percent_ranked_school_candidates_by_precinct <- ranked_school_candidates_by_precinct |>
  group_by(precinct)|>
      mutate(
           total_votes = votes_1 + votes_2 + votes_3 + votes_4 + votes_5 + votes_6,
           percent_votes_1 = round((votes_1/total_votes)*100),
           percent_votes_2 = round((votes_2/total_votes)*100),
           percent_votes_3 = round((votes_3/total_votes)*100),
           percent_votes_4 = round((votes_4/total_votes)*100),
           percent_votes_5 = round((votes_5/total_votes)*100),
           percent_votes_6 = round((votes_6/total_votes)*100)
     )|>
  select(
    precinct, 
    candidate_1, votes_1, percent_votes_1, 
    candidate_2, votes_2, percent_votes_2, 
    candidate_3, votes_3, percent_votes_3, 
    candidate_4, votes_4, percent_votes_4, 
    candidate_5, votes_5, percent_votes_5, 
    candidate_6, votes_6, percent_votes_6)

write_csv(percent_ranked_school_candidates_by_precinct, "percent_ranked_school_candidates_by_precinct.csv")
```

#PRESIDENTIAL RACE ANALYSIS BY PRECINCT
```{r}
general_president_clean <- general_2024|>
  select(precinct, president=president_and_vice_president_of_the_united_states_500001630)|>
  group_by(precinct, president)|>
     arrange(president)|>
  summarize(votes=n()) |>
  mutate(precinct= substring(precinct, 2))|>
  filter(
    !is.na(president),
    !president %in% c("undervote", "overvote", "or write-in:") #needs reporting to confirm accuracy
  ) |>
  group_by(precinct) |>
  arrange(desc(votes), .by_group = TRUE) |>
  mutate(rank = row_number()) |>
  ungroup()|>
  mutate(
    across(
            starts_with("president"),
               ~ trimws(gsub("\\s*\\([^)]*\\)", "",.x))))|>
  pivot_wider(
    names_from = rank,
    values_from = c(president, votes),
  names_glue = "{.value}_{rank}")|>
      mutate(
           total_votes = votes_1 + votes_2 + votes_3 + votes_4 + votes_5,
           percent_votes_1 = round((votes_1/total_votes)*100),
           percent_votes_2 = round((votes_2/total_votes)*100),
           percent_votes_3 = round((votes_3/total_votes)*100),
           percent_votes_4 = round((votes_4/total_votes)*100),
           percent_votes_5 = round((votes_5/total_votes)*100)
     )
  
write.csv(general_president_clean, "president_vote.csv", row.names = FALSE)

#how many precincts did harris win? 39
harris_win <- general_president_clean |>
  filter(president_1 == "Harris-Walz")|>
  select(precinct, president=president_1, harris_votes=votes_1, harris_percent=percent_votes_1)

#harris precincts + their school board results 
harris_w_board <- harris_win |>
  left_join( percent_ranked_school_candidates_by_precinct, by = "precinct")|>
  select(precinct, president, 
         candidate_1, 
         candidate_2,
         candidate_3)
         
#how many did she win that  voted for one of the conservative candidates? 15
harris_w_mol<- harris_w_board|> 
  filter(
    candidate_1 %in% c("Jaime Kiersten Brennan", "Colt Morningstar Black") | candidate_2 %in% c("Jaime Kiersten Brennan", "Colt Morningstar Black") | candidate_3 %in% c("Jaime Kiersten Brennan", "Colt Morningstar Black")
  )
```

## TOTAL SCHOOL BOARD VOTES BY CANDIDATE BAR CHART
```{r}
school_board_total <- school_board |>
  count(candidate, name = "votes") |>
  arrange(desc(votes))|>
   mutate(
    across(
      starts_with("candidate"),
      ~ trimws(gsub("\\s*\\([^)]*\\)", "",.x))
    ))

write_csv(school_board_total, "school_board_total.csv")
```









  